### ISSUE TITLE
ruuvilogger.py stops sending data

### ISSUE THREAD

**Issue by sirainen** [kipe/ruuvitag#1]
After running for a while it stops sending more data to influxdb. I guess influxdb doesn't like "nan":

InfluxDBClientError: 400: {"error":"unable to parse 'ruuvitag,address=d2:ec:07:ee:87:f0,movement_detected=false,protocol=3 acceleration_x=0.489,acceleration_y=0.885,acceleration_z=0.004,battery_voltage=2.911,humidity=90.0,measurement_sequence=0i,movement_counter=0i,pressure=1003.82,temperature=1.69,tx_power=nan 1549606251294753024': invalid number"}

**Comment by kipe** [comment]
Aah, you're correct... Those values really shouldn't even exist in the values dictionary, if protocol == 3. Fix coming right up.
